### ISSUE TITLE
Put downloads in releases and add a readme and license

### ISSUE THREAD

**Issue by vgturtle127** [braindx/vbjin-ovr#10]
I can add the readme and license, but I can't build the current version of VBjin-OVR because my current development machine is down at the moment.

Also, I can't find a mirror or anything of the VBjin-OVR 1.0 or 2.0 binary release.

**Comment by SigmaVirus** [comment]
Hi vgturtle127!

Through digging via Internet Archive I was able to access the vbjin-ovr code google page and find the link to the vbjin-ovr binaries both 1.0 and 2.0

https://drive.google.com/folderview?id=0B21bFUQjvxUecmZsUTFFWW5PVTg&usp=sharing

Hope it helps!

**Comment by vgturtle127** [comment]
@SigmaVirus What a nice Christmas present. :smile: 

Thanks, I tried that but I kept getting redirected and I spent like an hour trying to JavaScript my way out of that. Eventually I got tired of trying and gave up, and then I forgot about this.

Thanks so much! I am going to look into getting some of the other work done in this repo.

**Comment by SigmaVirus** [comment]
@vgturtle127

You're welcome!

Although I haven't used vbjin-ovr 1.0 for a while, I remember it to be quite good but 2.0 were broken from day 1 and could not even be started.

The saving issue in Virtual Boy Wario Land made me switch to the Mednafen VB core in Retroarch and I have even made a color change shader for it:

http://libretro.com/forums/showthread.php?t=4195

I'm not sure what will happen to the vbjin-ovr project and I never cared much for the occulus rift support to begin with but if someone could fix the saving issue in Wario Land that alone would be a huge step.

I wish you good luck on this task if you decide to work on vbjin-ovr!

**Comment by vgturtle127** [comment]
@SigmaVirus Well, I have every Virtual Boy ROM and all the homebrew, demos, etc. and I haven't noticed any problems with any of the games. I'm not sure if you knew this, but actually VBJin is based off of the Mednafen Virtual Boy core.

I couldn't download the color change shader because I don't have an account, could you upload it somewhere like Google Drive, Dropbox, etc.?

Let me look into the Wario Land issue, I'm sure it's trivial.

**Comment by SigmaVirus** [comment]
There's nothing wrong with the game play of Wario Land per sé in vbjin-ovr other than the saving part but you have to rely on save-states which I'm not to found about.

The Mednafen VB core for Retroarch have the saving issue fixed so maybe the solution is close?

Wario Land is the only game I own for Virtual Boy so I can't really say much for the rest of the VB library.

I don't know what the current status for vbjin-ovr is because it's been "dead" for a while and 2.0 haven't been fixed.

Anyway, here's the link for the shader:

http://www.filedropper.com/virtualboycolor

I wish you good luck on this and if you fix the saving issue then vbjin-ovr will be great.

**Comment by vgturtle127** [comment]
@SigmaVirus Thanks for the link. I am going to test VBJin soon hopefully, I am extremely busy at the moment. I will try to get to it today if I can. :smile:
